/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activity;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DJ RSK
 */
public class AddMedicinePanel extends javax.swing.JPanel {
    AddMedicinePanel addp;
    UpdateMedicinePanel updp;

    /**
     * Creates new form AddMedicinePanel
     */
    public AddMedicinePanel() {
        initComponents();
        this.setSize(490,390);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        addmedicine = new javax.swing.JButton();
        quantityfield = new javax.swing.JTextField();
        drugname = new javax.swing.JLabel();
        supname = new javax.swing.JLabel();
        AddDruglabel = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        supnamefield = new javax.swing.JTextField();
        cancelmed = new javax.swing.JButton();
        drugnamefield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(480, 360));
        setMinimumSize(new java.awt.Dimension(480, 360));
        setPreferredSize(new java.awt.Dimension(480, 360));

        addmedicine.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        addmedicine.setForeground(new java.awt.Color(0, 51, 51));
        addmedicine.setText("ADD");
        addmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmedicineActionPerformed(evt);
            }
        });
        addmedicine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addmedicineKeyPressed(evt);
            }
        });

        quantityfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantityfieldKeyPressed(evt);
            }
        });

        drugname.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        drugname.setForeground(new java.awt.Color(0, 51, 51));
        drugname.setText("Drug Name");

        supname.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        supname.setForeground(new java.awt.Color(0, 51, 51));
        supname.setText("Supplier Name");

        AddDruglabel.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        AddDruglabel.setForeground(new java.awt.Color(0, 51, 51));
        AddDruglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddDruglabel.setText("Add Drugs");

        quantity.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 51, 51));
        quantity.setText("Quantity");

        price.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        price.setForeground(new java.awt.Color(0, 51, 51));
        price.setText("Price (Per Piece)");

        supnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supnamefieldActionPerformed(evt);
            }
        });

        cancelmed.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        cancelmed.setForeground(new java.awt.Color(0, 51, 51));
        cancelmed.setText("CANCEL");
        cancelmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelmedActionPerformed(evt);
            }
        });
        cancelmed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelmedKeyPressed(evt);
            }
        });

        drugnamefield.setMinimumSize(new java.awt.Dimension(8, 20));
        drugnamefield.setPreferredSize(new java.awt.Dimension(8, 20));
        drugnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugnamefieldActionPerformed(evt);
            }
        });

        pricefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricefieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(AddDruglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drugname)
                        .addGap(56, 56, 56)
                        .addComponent(drugnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(supname)
                        .addGap(34, 34, 34)
                        .addComponent(supnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(price)
                        .addGap(22, 22, 22)
                        .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(quantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(addmedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelmed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AddDruglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drugname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addmedicine)
                    .addComponent(cancelmed))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drugnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugnamefieldActionPerformed

    private void supnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supnamefieldActionPerformed

    private void pricefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricefieldActionPerformed

    private void cancelmedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelmedKeyPressed
        new MedicinePanel().setVisible(true);        // TODO add your handling code here:

    }//GEN-LAST:event_cancelmedKeyPressed

    private void cancelmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelmedActionPerformed
        addp.setVisible(false);
        updp.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelmedActionPerformed

    private void addmedicineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addmedicineKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            Statement stmt = conn.createStatement();
            if((drugnamefield.getText().trim().length()!=0)&&(supnamefield.getText().trim().length()!=0)&&(pricefield.getText().trim().length()!=0)&&(quantityfield.getText().trim().length()!=0)){
                String drgnm= drugnamefield.getText();
                String supnm= supnamefield.getText();
                String prinm= pricefield.getText();
                String quanm= quantityfield.getText();
                int i =stmt.executeUpdate("insert into drugdata(DrugName,Supplier,Price,Quantity) values('"+drgnm+"','"+supnm+"','"+prinm+"','"+quanm+"')");
                if(i!=0){
                    JOptionPane.showMessageDialog(null,"Drug Added Successfully !");
                    drugnamefield.setText("");
                    supnamefield.setText("");
                    pricefield.setText("");
                    quantityfield.setText("");
                    }
            }
            else{
                JOptionPane.showMessageDialog(null,"Fill Compelete Details !");
                }
            
                conn.close();
            }
            catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } // TODO add your handling code here:
       }
    }//GEN-LAST:event_addmedicineKeyPressed

    private void addmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmedicineActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            Statement stmt = conn.createStatement();
            if((drugnamefield.getText().trim().length()!=0)&&(supnamefield.getText().trim().length()!=0)&&(pricefield.getText().trim().length()!=0)&&(quantityfield.getText().trim().length()!=0)){
                String drgnm= drugnamefield.getText();
                String supnm= supnamefield.getText();
                String prinm= pricefield.getText();
                String quanm= quantityfield.getText();
                
                int i =stmt.executeUpdate("insert into drugdata(DrugName,Supplier,Price,Quantity) values('"+drgnm+"','"+supnm+"','"+prinm+"','"+quanm+"')");
                if(i!=0){
                    JOptionPane.showConfirmDialog(this, "Want To Add?");
                    JOptionPane.showMessageDialog(null,"Drug Added Successfully !");
                    drugnamefield.setText("");
                    supnamefield.setText("");
                    pricefield.setText("");
                    quantityfield.setText("");
                    }
            }
            else{
                JOptionPane.showMessageDialog(null,"Fill Compelete Details !");
                }
            
                conn.close();
            }
            catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_addmedicineActionPerformed

    private void quantityfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityfieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            Statement stmt = conn.createStatement();
            if((drugnamefield.getText().trim().length()!=0)&&(supnamefield.getText().trim().length()!=0)&&(pricefield.getText().trim().length()!=0)&&(quantityfield.getText().trim().length()!=0)){
                String drgnm= drugnamefield.getText();
                String supnm= supnamefield.getText();
                String prinm= pricefield.getText();
                String quanm= quantityfield.getText();
                int i =stmt.executeUpdate("insert into drugdata(DrugName,Supplier,Price,Quantity) values('"+drgnm+"','"+supnm+"','"+prinm+"','"+quanm+"')");
                if(i!=0){
                    JOptionPane.showMessageDialog(null,"Drug Added Successfully !");
                    drugnamefield.setText("");
                    supnamefield.setText("");
                    pricefield.setText("");
                    quantityfield.setText("");
                    }
            }
            else{
                JOptionPane.showMessageDialog(null,"Fill Compelete Details !");
                }
            
                conn.close();
            }
            catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } // TODO add your handling code here:
       }// TODO add your handling code here:
    }//GEN-LAST:event_quantityfieldKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddDruglabel;
    private javax.swing.JButton addmedicine;
    private javax.swing.JButton cancelmed;
    private javax.swing.JLabel drugname;
    private javax.swing.JTextField drugnamefield;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel price;
    private javax.swing.JTextField pricefield;
    private javax.swing.JLabel quantity;
    private javax.swing.JTextField quantityfield;
    private javax.swing.JLabel supname;
    private javax.swing.JTextField supnamefield;
    // End of variables declaration//GEN-END:variables
}
