/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activity;

import java.awt.event.*;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;




/**
 *
 * @author DJ RSK
 */
public class HomePanel extends javax.swing.JPanel {
    String searchdata,cust,cont,addr;
    ResultSet rs;
    PreparedStatement pst;
    MedicinePanel medp = new MedicinePanel();

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        autoId();
        cidlabel.setVisible(false);
        cidfield.setVisible(false);
        myCombo();
    }
    
    private void autoId(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql = "select CID from customerdata order by CID desc limit 1";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String id = rs.getString("CID");
                int idn = Integer.parseInt(id);
                idn++;
                String uid = Integer.toString(idn);
                cidfield.setText(uid);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void myCombo(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql = "select * from drugdata";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String print = rs.getString("DrugName");
                drugcombo.addItem(print);     
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        cidfield = new javax.swing.JTextField();
        amnt = new javax.swing.JLabel();
        cidlabel = new javax.swing.JLabel();
        amntfield = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        drugcombo = new javax.swing.JComboBox();
        cstmrcntct = new javax.swing.JLabel();
        cstmraddrs = new javax.swing.JLabel();
        addrsfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cntctfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cstmrnm = new javax.swing.JLabel();
        buyitem = new javax.swing.JLabel();
        nmfield = new javax.swing.JTextField();
        quantity = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        searchc = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setMaximumSize(new java.awt.Dimension(837, 468));
        jPanel1.setMinimumSize(new java.awt.Dimension(837, 468));
        jPanel1.setPreferredSize(new java.awt.Dimension(837, 468));
        jPanel1.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OLD", "NEW" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(50, 70, 70, 30);

        cidfield.setEditable(false);
        cidfield.setMinimumSize(new java.awt.Dimension(8, 20));
        cidfield.setPreferredSize(new java.awt.Dimension(8, 20));
        cidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidfieldActionPerformed(evt);
            }
        });
        jPanel1.add(cidfield);
        cidfield.setBounds(200, 140, 120, 30);

        amnt.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        amnt.setForeground(new java.awt.Color(0, 51, 51));
        amnt.setText("Total Amount");
        jPanel1.add(amnt);
        amnt.setBounds(50, 340, 110, 30);

        cidlabel.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        cidlabel.setForeground(new java.awt.Color(0, 51, 51));
        cidlabel.setText("Customer Id");
        jPanel1.add(cidlabel);
        cidlabel.setBounds(50, 140, 88, 30);

        amntfield.setEditable(false);
        amntfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amntfieldActionPerformed(evt);
            }
        });
        jPanel1.add(amntfield);
        amntfield.setBounds(200, 340, 120, 30);
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(650, 110, 50, 30);

        drugcombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                drugcomboItemStateChanged(evt);
            }
        });
        drugcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugcomboActionPerformed(evt);
            }
        });
        jPanel1.add(drugcombo);
        drugcombo.setBounds(450, 110, 110, 30);

        cstmrcntct.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        cstmrcntct.setForeground(new java.awt.Color(0, 51, 51));
        cstmrcntct.setText("Contact No.");
        jPanel1.add(cstmrcntct);
        cstmrcntct.setBounds(50, 220, 86, 30);

        cstmraddrs.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        cstmraddrs.setForeground(new java.awt.Color(0, 51, 51));
        cstmraddrs.setText("Address");
        jPanel1.add(cstmraddrs);
        cstmraddrs.setBounds(50, 260, 58, 30);

        addrsfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrsfieldActionPerformed(evt);
            }
        });
        jPanel1.add(addrsfield);
        addrsfield.setBounds(200, 260, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug Name", "Quantity", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(358, 150, 452, 230);

        jButton3.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(740, 110, 70, 30);

        jButton5.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 51));
        jButton5.setText("PRINT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(303, 420, 80, 25);

        jButton4.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 51));
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(420, 420, 75, 25);

        cntctfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cntctfieldActionPerformed(evt);
            }
        });
        jPanel1.add(cntctfield);
        cntctfield.setBounds(200, 220, 120, 30);

        jLabel5.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Med Store Bill");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(332, 19, 180, 60);

        cstmrnm.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        cstmrnm.setForeground(new java.awt.Color(0, 51, 51));
        cstmrnm.setText("Customer Name");
        jPanel1.add(cstmrnm);
        cstmrnm.setBounds(50, 180, 115, 30);

        buyitem.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        buyitem.setForeground(new java.awt.Color(0, 51, 51));
        buyitem.setText("Drug Name");
        jPanel1.add(buyitem);
        buyitem.setBounds(360, 110, 84, 30);

        nmfield.setMinimumSize(new java.awt.Dimension(8, 20));
        nmfield.setPreferredSize(new java.awt.Dimension(8, 20));
        nmfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmfieldActionPerformed(evt);
            }
        });
        jPanel1.add(nmfield);
        nmfield.setBounds(200, 180, 120, 30);

        quantity.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 51, 51));
        quantity.setText("Quantity");
        jPanel1.add(quantity);
        quantity.setBounds(580, 110, 70, 30);

        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        jPanel1.add(searchfield);
        searchfield.setBounds(150, 110, 100, 30);

        searchc.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        searchc.setForeground(new java.awt.Color(0, 51, 51));
        searchc.setText("Customer Id");
        jPanel1.add(searchc);
        searchc.setBounds(50, 110, 90, 30);

        jButton1.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 110, 60, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prj.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 852, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nmfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmfieldActionPerformed

    private void cntctfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cntctfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cntctfieldActionPerformed

    private void addrsfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrsfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrsfieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        nmfield.setText("");
        cntctfield.setText("");
        addrsfield.setText("");
        searchfield.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){   
            nmfield.setText("");
            cntctfield.setText("");
            addrsfield.setText("");
            searchfield.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql="select * from drugdata where DrugName='"+drugcombo.getSelectedItem()+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
    }//GEN-LAST:event_jButton3KeyPressed

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            searchdata= searchfield.getText();
            if(searchdata.trim().length()!=0){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql="select * from customerdata where CID='"+searchdata+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                cust = rs.getString("CustomerName");
                cont = rs.getString("Contact");
                addr = rs.getString("Address");
                nmfield.setText(cust);
                cntctfield.setText(cont);
                addrsfield.setText(addr);
                
            }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            }
            else{
                    JOptionPane.showMessageDialog(null, "Enter Customer ID To Search ");
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5KeyPressed

    private void drugcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugcomboActionPerformed

    private void drugcomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_drugcomboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_drugcomboItemStateChanged

    private void amntfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amntfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amntfieldActionPerformed

    private void cidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidfieldActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        Object a = jComboBox1.getSelectedItem();
        if(a=="NEW"){
            autoId();
            cidlabel.setVisible(true);
            cidfield.setVisible(true);  
            searchc.setVisible(false);
            searchfield.setVisible(false);
            jButton1.setVisible(false);
        }
        else{
            cidlabel.setVisible(false);
            cidfield.setVisible(false);  
            searchc.setVisible(true);
            searchfield.setVisible(true);
            jButton1.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrsfield;
    private javax.swing.JLabel amnt;
    private javax.swing.JTextField amntfield;
    private javax.swing.JLabel buyitem;
    private javax.swing.JTextField cidfield;
    private javax.swing.JLabel cidlabel;
    private javax.swing.JTextField cntctfield;
    private javax.swing.JLabel cstmraddrs;
    private javax.swing.JLabel cstmrcntct;
    private javax.swing.JLabel cstmrnm;
    private javax.swing.JComboBox drugcombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nmfield;
    private javax.swing.JLabel quantity;
    private javax.swing.JLabel searchc;
    private javax.swing.JTextField searchfield;
    // End of variables declaration//GEN-END:variables
}
