/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activity;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author DJ RSK
 */
public class MedicinePanel extends javax.swing.JPanel{
AddMedicinePanel addp;
UpdateMedicinePanel updp;
GridBagLayout lay = new GridBagLayout();
ResultSet rs;
String tableClicked,drug,supname,price,quantity,searchdata;
        
    
    /**
     * Creates new form MedicinePanel
     */
    public MedicinePanel() {
        initComponents();
        updateTable();
        addp=new AddMedicinePanel();
        updp=new UpdateMedicinePanel();
        tableClicked = "";
        GridBagConstraints gc= new GridBagConstraints();
        trnsprnt.setLayout(lay);
        trnsprnt.setSize(450,360);
        gc.gridx=0;
        gc.gridy=0;
        trnsprnt.add(addp,gc);
        gc.gridx=0;
        gc.gridy=0;
        trnsprnt.add(updp,gc);
        trnsprnt.setVisible(false);
        addp.setVisible(true);
        updp.setVisible(false);
        jScrollPane1.setVisible(true);
        
    }
    public void updateTable(){
   
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql = "SELECT * FROM drugdata";
            PreparedStatement pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clearbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        adddrug = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        trnsprnt = new javax.swing.JPanel();
        updatedrug = new javax.swing.JButton();
        deletedrug = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));
        setMaximumSize(new java.awt.Dimension(837, 468));
        setMinimumSize(new java.awt.Dimension(837, 468));

        jPanel1.setLayout(null);

        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        clearbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearbtnKeyPressed(evt);
            }
        });
        jPanel1.add(clearbtn);
        clearbtn.setBounds(700, 30, 30, 30);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(490, 390));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(490, 390));

        jTable1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(51, 102, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(1, 2));
        jTable1.setMaximumSize(new java.awt.Dimension(450, 360));
        jTable1.setMinimumSize(new java.awt.Dimension(450, 360));
        jTable1.setPreferredSize(new java.awt.Dimension(490, 390));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 80, 480, 360);

        adddrug.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        adddrug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        adddrug.setText("  ADD");
        adddrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddrugActionPerformed(evt);
            }
        });
        jPanel1.add(adddrug);
        adddrug.setBounds(610, 130, 140, 50);

        jButton1.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 30, 60, 29);

        jLabel2.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel2.setText("Search Drug");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 30, 100, 30);

        searchfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchfieldMouseClicked(evt);
            }
        });
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        searchfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchfieldKeyPressed(evt);
            }
        });
        jPanel1.add(searchfield);
        searchfield.setBounds(210, 30, 410, 30);

        trnsprnt.setMaximumSize(new java.awt.Dimension(480, 360));

        javax.swing.GroupLayout trnsprntLayout = new javax.swing.GroupLayout(trnsprnt);
        trnsprnt.setLayout(trnsprntLayout);
        trnsprntLayout.setHorizontalGroup(
            trnsprntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        trnsprntLayout.setVerticalGroup(
            trnsprntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel1.add(trnsprnt);
        trnsprnt.setBounds(80, 80, 480, 360);

        updatedrug.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        updatedrug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        updatedrug.setText("UPDATE");
        updatedrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedrugActionPerformed(evt);
            }
        });
        jPanel1.add(updatedrug);
        updatedrug.setBounds(610, 310, 140, 50);

        deletedrug.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        deletedrug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        deletedrug.setText("DELETE");
        deletedrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedrugActionPerformed(evt);
            }
        });
        jPanel1.add(deletedrug);
        deletedrug.setBounds(610, 220, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prj.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletedrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedrugActionPerformed
        jScrollPane1.setVisible(true);
        trnsprnt.setVisible(false);
        if ("".equals(tableClicked)){
                JOptionPane.showMessageDialog(null, "Please select a Drug to delete!");
         }else{
             int des = JOptionPane.showConfirmDialog(null, "Are you sure want to delete this Drug?","Delete",JOptionPane.YES_NO_OPTION);
             if (des==0){
                   try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
                    String sql = "DELETE FROM drugdata WHERE DrugName='"+tableClicked+"'";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    pst.close();
                    rs.close();
                    JOptionPane.showMessageDialog(null, "Drug has been deleted!");
                    updateTable();
               }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
                }
             }
            
         }
            // TODO add your handling code here:
    }//GEN-LAST:event_deletedrugActionPerformed

    private void adddrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddrugActionPerformed
        jScrollPane1.setVisible(false);
        trnsprnt.setVisible(true);
        addp.setVisible(true);
        updp.setVisible(false);  
        
       // TODO add your handling code here:
    }//GEN-LAST:event_adddrugActionPerformed

    private void updatedrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedrugActionPerformed

        jScrollPane1.setVisible(true);
        trnsprnt.setVisible(false);
        if ("".equals(tableClicked)){
                JOptionPane.showMessageDialog(null, "Please select a Drug to update!");
            }
        else{
                jScrollPane1.setVisible(false);
                trnsprnt.setVisible(true);
                addp.setVisible(false);
                updp.setVisible(true);     
        
                updp.drug = this.drug;
                updp.updatenamefield.setText(drug);
                updp.updatesupfield.setText(supname);
                updp.updatequantityfield.setText(quantity);
                updp.updatepricefield.setText(price);
            }
          // TODO add your handling code here:
    }//GEN-LAST:event_updatedrugActionPerformed

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            searchdata= searchfield.getText();
            if(searchdata.trim().length()!=0){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql="select * from drugdata where DrugName='"+searchdata+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            }
            else{
                    JOptionPane.showMessageDialog(null, "Enter Drug Name To Search ");
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int row = jTable1.getSelectedRow();
            tableClicked = (jTable1.getModel().getValueAt(row, 0).toString());
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql = "SELECT * FROM drugdata WHERE DrugName =  '"+ tableClicked +"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                drug = rs.getString("DrugName");
                supname = rs.getString("Supplier");
                quantity = rs.getString("Quantity");
                price = rs.getString("Price");

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        searchfield.setText("");
        updateTable();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void searchfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        searchdata= searchfield.getText();
            if(searchdata.trim().length()!=0){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql="select * from drugdata where DrugName='"+searchdata+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            }
            else{
                    JOptionPane.showMessageDialog(null, "Enter Drug Name To Search ");
                    }
        }
    }//GEN-LAST:event_searchfieldKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            searchdata= searchfield.getText();
            if(searchdata.trim().length()!=0){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql="select * from drugdata where DrugName='"+searchdata+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            }
            else{
                    JOptionPane.showMessageDialog(null, "Enter Drug Name To Search ");
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void clearbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearbtnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            searchfield.setText("");
            updateTable();
        }
    }//GEN-LAST:event_clearbtnKeyPressed

    private void searchfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchfieldMouseClicked
        jScrollPane1.setVisible(true);
        trnsprnt.setVisible(false);
        updateTable();
    }//GEN-LAST:event_searchfieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddrug;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton deletedrug;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchfield;
    private javax.swing.JPanel trnsprnt;
    private javax.swing.JButton updatedrug;
    // End of variables declaration//GEN-END:variables
}
