/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activity;

import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author DJ RSK
 */
public class UpdateMedicinePanel extends javax.swing.JPanel {
    String drug;

    /**
     *
     */
    /**
     * Creates new form UpdateMedicinePanel
     */
    public UpdateMedicinePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddDruglabel = new javax.swing.JLabel();
        drugname = new javax.swing.JLabel();
        updatenamefield = new javax.swing.JTextField();
        supname = new javax.swing.JLabel();
        updatesupfield = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        updatepricefield = new javax.swing.JTextField();
        quantity = new javax.swing.JLabel();
        updatequantityfield = new javax.swing.JTextField();
        updatemedicine = new javax.swing.JButton();
        cancelmed = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(480, 360));
        setMinimumSize(new java.awt.Dimension(480, 360));
        setPreferredSize(new java.awt.Dimension(480, 360));

        AddDruglabel.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        AddDruglabel.setForeground(new java.awt.Color(0, 51, 51));
        AddDruglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddDruglabel.setText("Update Drugs");

        drugname.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        drugname.setForeground(new java.awt.Color(0, 51, 51));
        drugname.setText("Drug Name");

        updatenamefield.setMinimumSize(new java.awt.Dimension(8, 20));
        updatenamefield.setPreferredSize(new java.awt.Dimension(8, 20));
        updatenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenamefieldActionPerformed(evt);
            }
        });

        supname.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        supname.setForeground(new java.awt.Color(0, 51, 51));
        supname.setText("Supplier Name");

        updatesupfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatesupfieldActionPerformed(evt);
            }
        });

        price.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        price.setForeground(new java.awt.Color(0, 51, 51));
        price.setText("Price (Per Piece)");

        updatepricefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepricefieldActionPerformed(evt);
            }
        });

        quantity.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 51, 51));
        quantity.setText("Quantity");

        updatequantityfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updatequantityfieldKeyPressed(evt);
            }
        });

        updatemedicine.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        updatemedicine.setForeground(new java.awt.Color(0, 51, 51));
        updatemedicine.setText("UPDATE");
        updatemedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemedicineActionPerformed(evt);
            }
        });
        updatemedicine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updatemedicineKeyPressed(evt);
            }
        });

        cancelmed.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        cancelmed.setForeground(new java.awt.Color(0, 51, 51));
        cancelmed.setText("CANCEL");
        cancelmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelmedActionPerformed(evt);
            }
        });
        cancelmed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelmedKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(AddDruglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drugname)
                        .addGap(56, 56, 56)
                        .addComponent(updatenamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(supname)
                        .addGap(34, 34, 34)
                        .addComponent(updatesupfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(price)
                        .addGap(22, 22, 22)
                        .addComponent(updatepricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(updatequantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(updatemedicine)
                        .addGap(18, 18, 18)
                        .addComponent(cancelmed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AddDruglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drugname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatenamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatesupfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatepricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatequantityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatemedicine)
                    .addComponent(cancelmed))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatenamefieldActionPerformed

    private void updatesupfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatesupfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatesupfieldActionPerformed

    private void updatepricefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepricefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatepricefieldActionPerformed

    private void updatequantityfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updatequantityfieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql  = "UPDATE drugdata SET DrugName='"+ updatenamefield.getText() +"',Supplier='"+ updatesupfield.getText() +"',Price='"+ updatepricefield.getText() +"',Quantity='"+ updatequantityfield.getText() +"' WHERE DrugName='"+ drug +"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            conn.close();
            JOptionPane.showMessageDialog(null, "Drug has been updated!");
            drug = updatenamefield.getText();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
            }   
        }
    }//GEN-LAST:event_updatequantityfieldKeyPressed

    private void updatemedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemedicineActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql  = "UPDATE drugdata SET DrugName='"+ updatenamefield.getText() +"',Supplier='"+ updatesupfield.getText() +"',Price='"+ updatepricefield.getText() +"',Quantity='"+ updatequantityfield.getText() +"' WHERE DrugName='"+ drug +"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            conn.close();
            JOptionPane.showMessageDialog(null, "Drug has been updated!");
            drug = updatenamefield.getText();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }      // TODO add your handling code here:
    }//GEN-LAST:event_updatemedicineActionPerformed

    private void updatemedicineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updatemedicineKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            String sql  = "UPDATE drugdata SET DrugName='"+ updatenamefield.getText() +"',Supplier='"+ updatesupfield.getText() +"',Price='"+ updatepricefield.getText() +"',Quantity='"+ updatequantityfield.getText() +"' WHERE DrugName='"+ drug +"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            conn.close();
            JOptionPane.showMessageDialog(null, "Drug has been updated!");
            drug = updatenamefield.getText();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
            }   
        }
    }//GEN-LAST:event_updatemedicineKeyPressed

    private void cancelmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelmedActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cancelmedActionPerformed

    private void cancelmedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelmedKeyPressed
        new MedicinePanel().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelmedKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddDruglabel;
    private javax.swing.JButton cancelmed;
    private javax.swing.JLabel drugname;
    private javax.swing.JLabel price;
    private javax.swing.JLabel quantity;
    private javax.swing.JLabel supname;
    private javax.swing.JButton updatemedicine;
    public javax.swing.JTextField updatenamefield;
    public javax.swing.JTextField updatepricefield;
    public javax.swing.JTextField updatequantityfield;
    public javax.swing.JTextField updatesupfield;
    // End of variables declaration//GEN-END:variables
}
