/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activity;

import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author DJ RSK
 */
public class UserPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    public UserPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        flnm = new javax.swing.JTextField();
        usrnm2 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pswd2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(837, 480));

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_127px.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 130, 150);

        jLabel5.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add User");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 30, 180, 60);

        jLabel8.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Full Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 110, 76, 30);

        jLabel10.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Username");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 150, 71, 30);

        jLabel9.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Email");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 190, 41, 30);

        jLabel7.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 230, 67, 30);

        flnm.setMinimumSize(new java.awt.Dimension(8, 20));
        flnm.setPreferredSize(new java.awt.Dimension(8, 20));
        flnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flnmActionPerformed(evt);
            }
        });
        jPanel1.add(flnm);
        flnm.setBounds(320, 110, 120, 30);

        usrnm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrnm2ActionPerformed(evt);
            }
        });
        jPanel1.add(usrnm2);
        usrnm2.setBounds(320, 150, 120, 30);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(320, 190, 120, 30);

        pswd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswd2KeyPressed(evt);
            }
        });
        jPanel1.add(pswd2);
        pswd2.setBounds(320, 230, 120, 30);

        jButton3.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(230, 290, 63, 25);

        jButton4.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 51));
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(330, 290, 75, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prj.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(837, 480));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 837, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flnmActionPerformed

    private void usrnm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrnm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrnm2ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void pswd2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswd2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
                Statement stmt = conn.createStatement();
                if((flnm.getText().trim().length()!=0)&&(usrnm2.getText().trim().length()!=0)&&(email.getText().trim().length()!=0)&&(pswd2.getText().trim().length()>=6)){
                    String nm= flnm.getText();
                    String usr= usrnm2.getText();
                    String eml= email.getText();
                    String pd= pswd2.getText();
                    int i =stmt.executeUpdate("insert into userdata(FullName,Username,Email,Password) values('"+nm+"','"+usr+"','"+eml+"','"+pd+"')");
                    if(i!=0){
                        JOptionPane.showMessageDialog(null,"User Added Successfully !");
                        flnm.setText("");
                        usrnm2.setText("");
                        email.setText("");
                        pswd2.setText("");
                    }
                }
                else{
                    if((flnm.getText().trim().length()!=0)&&(usrnm2.getText().trim().length()!=0)&&(email.getText().trim().length()!=0)&&(pswd2.getText().trim().length()<6)){
                        JOptionPane.showMessageDialog(null,"Create Password with Atleast 6 Characters !");
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Fill All Values !");
                    }
                }
                conn.close();
            }
            catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_pswd2KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        flnm.setText("");
        usrnm2.setText("");
        email.setText("");
        pswd2.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            flnm.setText("");
            usrnm2.setText("");
            email.setText("");
            pswd2.setText("");
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
                Statement stmt = conn.createStatement();
                if((flnm.getText().trim().length()!=0)&&(usrnm2.getText().trim().length()!=0)&&(email.getText().trim().length()!=0)&&(pswd2.getText().trim().length()>=6)){
                    String nm= flnm.getText();
                    String usr= usrnm2.getText();
                    String eml= email.getText();
                    String pd= pswd2.getText();
                    int i =stmt.executeUpdate("insert into userdata(FullName,Username,Email,Password) values('"+nm+"','"+usr+"','"+eml+"','"+pd+"')");
                    if(i!=0){
                        JOptionPane.showMessageDialog(null,"User Added Successfully !");
                        flnm.setText("");
                        usrnm2.setText("");
                        email.setText("");
                        pswd2.setText("");
                    }
                }
                else{
                    if((flnm.getText().trim().length()!=0)&&(usrnm2.getText().trim().length()!=0)&&(email.getText().trim().length()!=0)&&(pswd2.getText().trim().length()<6)){
                        JOptionPane.showMessageDialog(null,"Create Password with Atleast 6 Characters !");
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Fill All Values !");
                    }
                }
                conn.close();
            }
            catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mymed","root","");
            Statement stmt = conn.createStatement();
            if((flnm.getText().trim().length()!=0)&&(usrnm2.getText().trim().length()!=0)&&(email.getText().trim().length()!=0)&&(pswd2.getText().trim().length()>=6)){
                String nm= flnm.getText();
                String usr= usrnm2.getText();
                String eml= email.getText();
                String pd= pswd2.getText();
                int i =stmt.executeUpdate("insert into userdata(FullName,Username,Email,Password) values('"+nm+"','"+usr+"','"+eml+"','"+pd+"')");
                if(i!=0){
                    JOptionPane.showMessageDialog(null,"User Added Successfully !");
                    flnm.setText("");
                    usrnm2.setText("");
                    email.setText("");
                    pswd2.setText("");
                }}
                else{
                    if((flnm.getText().trim().length()!=0)&&(usrnm2.getText().trim().length()!=0)&&(email.getText().trim().length()!=0)&&(pswd2.getText().trim().length()<6)){
                        JOptionPane.showMessageDialog(null,"Create Password with Atleast 6 Characters !");
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Fill All Values !");
                    }
                }
                conn.close();
            }
            catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JTextField flnm;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pswd2;
    private javax.swing.JTextField usrnm2;
    // End of variables declaration//GEN-END:variables
}
